### ISSUE TITLE
Image initial position?

### ISSUE THREAD

**Issue by chez14** [RRutsche/react-parallax#27]
Can we set an initial position for the image?

like, it start with `top=100px`... so scroll on 100 to something?

**Comment by rrutsche** [comment]
Hi @chez14 
Sorry for the late response. I will have to try if this is working in practice. It will affect the strength of the translation. And I also have to try if this is working with negative strength values. So in general it should be possible to add some kind of starting point. But I guess there are some cases I need to check before adding a new prop for it.

**Comment by chez14** [comment]
Ok, no prob! Thanks!

**Comment by cknific** [comment]
This would be great! +1

**Comment by ghost** [comment]
I agree +1

**Comment by seblaz** [comment]
Would be nice +1

**Comment by xstable** [comment]
Any progress here?
Not 100% sure, if thread-opener means this, but I found that the image doesn't start at the same position if you have different Screen-width:
![screenshot_ 9_09_55](https://user-images.githubusercontent.com/1778068/87218806-6a861f80-c356-11ea-91dc-3b32000904b4.jpg)

I would love to see that there is an option to place the Image to define where it should be start if the Parallax-Element come into view.

**Comment by rrutsche** [comment]
Hey folks, sorry for the delay. 
This issue is open for quite a while and I don't really know if it's worth to introduce such an initial position. Maybe let's discuss your use cases so I can understand a bit better. Because from my understanding the "initial position" would be the starting point when the image enters the screen while scrolling (bottom of viewport). But is this really what it is meant to be? I could also imagine that someone would like to steer the image position when its position is at the top of the viewport. So tell me 🙂 . The thing is, that there are so many different use cases which we cannot cover with one prop. And I fear that we will have a component which tries to solve everything but nothing really good.

The other point: I created a release candidate `3.0.4-rc.0` which hopefully solves the positioning on different screen sizes @xstable mentioned. Originally the calculation of the relative position was based on the `viewport height + parallax content height`. So if you think of the scroll position as percentage value: 
- `0` -> top of the parallax component enters the screen when scrolling up
- `1` -> bottom of parallax leaves the screen (top of the viewport)

This was to prevent white background getting visible before the image leaves the screen. I checked the issue @xstable posted and decided that it's also okay to only use the `viewport height` for calculation. White space would still not get visible as this part of the component is not in viewport anymore. This way you don't have different positions on different screens. 

Can you check the release candidate `3.0.4-rc.0` on `npm`?

Thanks

**Comment by xstable** [comment]
Seems to be better now with 3.0.4-rc.0

**Comment by alsantos123** [comment]
Having same than @xstable.

3.0.4-rc.0 was exatcly what I needed.

Thanks.
