### ISSUE TITLE
Server rendering

### ISSUE THREAD

**Issue by SPAHI4** [RRutsche/react-parallax#6]
```
ReferenceError: window is not defined
    at Parallax.getWindowHeight (.../node_modules/react-parallax/dist/Parallax.js:284:12)
```

**Comment by rrutsche** [comment]
@SPAHI4 thanks for your feedback. Did not try server side rendering yet. Can you provide a minimal example for testing? Thinking about mocking the window/document objects. It's browserify that complains, is it?

**Comment by SPAHI4** [comment]
No, it is webpack. I use this boilerplate https://github.com/iam4x/isomorphic-flux-boilerplate

**Comment by Viscosity4373** [comment]
+1 Same problem with server side rendering because there's no window or document variable in node.

I used this workaround for now:

``` javascript
const canUseDOM = !!(
  (typeof window !== 'undefined' &&
  window.document && window.document.createElement)
);
```

and then in the component where I want to use Parallax:

``` javascript
{ canUseDOM ?
          <Parallax bgImage="images/clouds.jpg">{ content }</Parallax>
          : <div className="parallax-replacement">{ content }</div>}
```

Only problem with that is, that I get different markup on client and server, which react then complains about in the console.
Ideally the _disabled_ prop would deactivate all code that uses window or document and still return the same general layout of the markup (i.e. the same _div_ and _img_ tags with the react-parallax classNames).

**Comment by rrutsche** [comment]
[v0.3.2](https://github.com/RRutsche/react-parallax/releases/tag/v0.3.2) should fix the issue. 
@fargerio I added DOM check like in your example whenever window object is gonna be used.

I also put the event listener binding to componentDidMount instead of componentWillMount so server/client markup is consistent. 

Btw, I tested the component with https://github.com/iam4x/isomorphic-flux-boilerplate and even without any changes it did not throw an error. It just complained about different markup. Used react version 0.14.3. 
However I hope the changes will solve the problem.

**Comment by Viscosity4373** [comment]
Thank you, great work. Now it works perfectly for me.

**Comment by Viscosity4373** [comment]
One more thing: 
Im using the Component in a site that has to look as similar as possible when js is deactivated. Right now the img tag shows before the content  and moves it down. 
To avoid this I add the following css class to the component when doing server side rendering:

``` less
.react-parallax-ssr {
  background-size: cover;
  background-attachment: fixed;
  background-image: url(/images/bg-image.jpg);
  .react-parallax-bgimage {
    display: none;
  }
}
```

You might want to do something similar when _disabled_ is true.

**Comment by rrutsche** [comment]
Thanks for the approach. This is indeed a good point. Will add this in one of the next releases.
